### ISSUE TITLE
Can not Run

### ISSUE THREAD

**Issue by abdul-qadirdeveloper** [mmacneil/AngularASPNETCoreAuthentication#1]
After clonning I can not run.
I followed following sequence after clone
1. npm install
2. dotnet restore
3. dotnet build
it fails when it build angular part of the project
if i run this command 
npm run build
it shows the same set of errors
Versions
node: 7.7.2
npm: 3.10..8
ng: 1,2,6
dotnet: 1.0.4

**Comment by mmacneil** [comment]
Closing, this will also occur if you don't `npm install` first.
