### ISSUE TITLE
for upgrade to dot net core 2

### ISSUE THREAD

**Issue by javadmjt** [mmacneil/AngularASPNETCoreAuthentication#3]
in ConfigureServices
```
    services.AddAuthentication(jwt =>
        {
          jwt.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
          jwt.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
        })
        .AddJwtBearer(jwt =>
        {
          jwt.TokenValidationParameters = new TokenValidationParameters
          {
            ValidateIssuer = true,
            ValidIssuer = jwtAppSettingOptions[nameof(JwtIssuerOptions.Issuer)],

            ValidateAudience = true,
            ValidAudience = jwtAppSettingOptions[nameof(JwtIssuerOptions.Audience)],

            ValidateIssuerSigningKey = true,
            IssuerSigningKey = _signingKey,

            RequireExpirationTime = false,
            ValidateLifetime = false,
            ClockSkew = TimeSpan.Zero
          };
        });
```
and in Configure

`  app.UseAuthentication();`

**Comment by fersaccon** [comment]
I had problems to authenticate in .NET Core 2. Your suggestion solved the token generation, but to authenticate I got the answer was 404 - Not found, if the controller was secured. I solved by changing the DashboardController decoration from [Authorize(Policy = "ApiUser")]
to
[Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]. 

I just followed this post:
https://wildermuth.com/2017/08/19/Two-AuthorizationSchemes-in-ASP-NET-Core-2

**Comment by Sweens** [comment]
@javadmjt  you just simply replaced the service.AddAuthentication section? The var jwtSettingOptions, and service.Configure<JwtIssurOptions> portions still exist in the ConfigureServices method correct?

I have tried this but the api post still doesn't work. I have successfully created a user, but if I put a break point in the AuthController Post method it never gets hit and I just get 500 errors back from postman.

**Comment by fatihkaratay** [comment]
Well, tried that and every time, I receive 401 error even with the valid jwt token.

**Comment by mmacneil** [comment]
I created a new post and repo based on ASP.NET Core 2.0.  See [JWT Authentication with ASP.NET Core 2 Web API, Angular 5, .NET Core Identity and Facebook Login](https://fullstackmark.com/post/13/jwt-authentication-with-aspnet-core-2-web-api-angular-5-net-core-identity-and-facebook-login)
